from pbixray import PBIXRay
from icecream import ic

# PBIX_FILE_PATH = r"data/Excalidraw.pbix"
PBIX_FILE_PATH = r"data/Sales & Returns Sample v201912.pbix"
model = PBIXRay(PBIX_FILE_PATH)
ic(model.tables)
ic(model.metadata)
ic(model.power_query)
ic(model.statistics)
ic(model.dax_tables)
ic(model.dax_measures)
ic(model.size)
ic(model.schema)
ic(model.relationships)
ic(model.rls)
ic(model.get_table("Age"))
PBIX_FILE_PATH = r"data/Adventure Works DW 2020.pbix"
model = PBIXRay(PBIX_FILE_PATH)
ic(model.tables)
ic(model.metadata)
ic(model.power_query)
ic(model.statistics)
ic(model.dax_tables)
ic(model.dax_measures)
ic(model.size)
ic(model.schema)
ic(model.relationships)
ic(model.get_table("Sales Order"))
model = PBIXRay(r"data/Excalidraw.pbix")
ic(model.tables)
ic(model.metadata)
ic(model.power_query)
ic(model.statistics)
ic(model.dax_tables)
ic(model.dax_measures)
ic(model.size)
ic(model.schema)
ic(model.relationships)
ic(model.dax_columns)
ic(model.get_table("Fruit_RLE"))

model = PBIXRay(r"data/2020SU11 Blog Demo - November.pbix")
ic(model.tables)
ic(model.metadata)
ic(model.power_query)
ic(model.statistics)
ic(model.dax_tables)
ic(model.dax_measures)
ic(model.dax_columns)
ic(model.size)
ic(model.schema)
ic(model.relationships)
ic(model.get_table("Reseller"))

model = PBIXRay(r"data/2020SU11 Blog Demo - November.pbix")
ic(model.tables)
ic(model.metadata)
ic(model.m_parameters)
ic(model.statistics)

model = PBIXRay(r"data/old-Supplier-Quality-Analysis-Sample-PBIX.pbix")
ic(model.tables)
ic(model.metadata)
ic(model.m_parameters)
ic(model.statistics)
ic(model.dax_tables)
ic(model.dax_measures)
ic(model.dax_columns)
ic(model.size)
ic(model.schema)
ic(model.relationships)
ic(model.get_table("Vendor"))